# Generated by Django 5.0.6 on 2024-06-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
